---
#service
apiVersion: v1
kind: Service
metadata:
  name: ktcloud-svc
spec:
  selector:
    color: blue
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer



---
#deployment : blue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktcloud-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      labels:
        color: blue
    spec:
      containers:
      - name: ktcloudctn-blue
        image: gne0hy/ktcloudinfra:blue
        resources:
          limits:
            memory: "32Mi"
            cpu: "250m"
        ports:
        - containerPort: 80

---
#keda

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cron-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: ktcloudctn-blue # ScaledObject가 대상으로 하는 Deployment 이름
  pollingInterval: 30  # KEDA가 상태를 확인하는 주기 (초)
  cooldownPeriod: 300  # 마지막 스케일 후 안정화를 위한 대기 시간 (초)
  minReplicaCount: 3   # 최소 Pod 수
  maxReplicaCount: 5  # 최대 Pod 수
  triggers:
  - type: cron  # 시간에 다른 스케일 조정
    metadata:
      timezone: "Asia/Seoul"  # 원하는 시간대
      start: "46 * * * *"      # 시작 시점 (Cron 표현식)
      end: "50 * * * *"       # 종료 시점 (Cron 표현식)
      desiredReplicas: "6"    # 스케일링할 Pod 수

